### ISSUE TITLE
Update Nuget Package

### ISSUE THREAD

**Issue by steve-haar** [shipstation/shipengine-csharp#5]
The nuget package ShipEngine.ApiClient was last published on May 30, 2017 and it doesn't have all the new features that have been added to this repo. Could you please update the nuget package?

**Comment by jamesbar2** [comment]
Hey @steve-haar, we're working on an updated version of this now and it should be released soon!

**Comment by jamesbar2** [comment]
@steve-haar We've updated our SDK, it's available on Nuget here:
https://www.nuget.org/packages/ShipEngine.ApiClient/1.2.29

You can also view the release, here: https://github.com/shipstation/shipengine-csharp/releases/tag/1.2.29

Thanks for your patience!

**Comment by airduster** [comment]
Tried to install this SDK from nuget just now getting the following error message. 

> "Could not install package 'ShipEngine.ApiClient 1.2.29'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."

Project page .NET framework 4.0 is supported is this a bug related to recent changes made?

**Comment by bill-robbins-ss** [comment]
Hi @airduster the SDK was built targeting v4.5 - there was an oversight with the README saying 4.0 is supported. 

If you need 4.0 support you can clone this repository and retarget for 4.0 but be aware you'll need to re-add NuGet dependencies.

**Comment by airduster** [comment]
Re-added the NuGet dependencies for switching to .NET 4.0 build but the SDK uses many "Since 4.5" only reflection logic in JsonSubTypes.cs such as IReadOnlyDictionary<> and type.GetTypeInfo() that are only available in .NET 4.5. 

I'm sure I could refactor the logic to hack and make it work but it's not a simple rebuild then
